services:
  api_users:
    container_name: api_users
    build:
      context: .
      target: dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - ${APP_PORT}:8000
    command: uv run manage.py runserver 0.0.0.0:8000
    networks:
      - nginx-proxy


networks:
  nginx-proxy:
      external: true
